# Generated by Django 3.2.7 on 2022-03-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_studies',
            field=models.ManyToManyField(blank=True, related_name='user_current_studies', to='hl.StudyProgramme'),
        ),
        migrations.AddField(
            model_name='profile',
            name='past_studies',
            field=models.ManyToManyField(blank=True, related_name='user_past_studies', to='hl.StudyProgramme'),
        ),
    ]
