# Generated by Django 3.2.7 on 2022-03-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hl', '0002_auto_20220309_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyprogramme',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='skills_studies', to='hl.Skill'),
        ),
    ]
