# Generated by Django 3.2.7 on 2022-03-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hl', '0003_studyprogramme_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyprogramme',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
