# Generated by Django 3.2.7 on 2022-03-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hl', '0004_alter_studyprogramme_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.URLField(blank=True, max_length=150, null=True),
        ),
    ]
