# Generated by Django 3.2.7 on 2022-03-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hl', '0006_auto_20220311_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='level',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='subscribers',
        ),
        migrations.RemoveField(
            model_name='studyprogramme',
            name='subscribers',
        ),
        migrations.AddField(
            model_name='question',
            name='online',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.IntegerField(choices=[(0, 'pending'), (1, 'in progress'), (2, 'answered')], default=0, null=True),
        ),
    ]
