# Generated by Django 3.2.7 on 2022-03-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hl', '0009_alter_question_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='online',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
