# Generated by Django 3.2.7 on 2022-03-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hl', '0010_alter_question_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
