# Generated by Django 3.2.7 on 2022-03-20 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hl', '0013_auto_20220320_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_notification', to='hl.question'),
        ),
    ]
