# Generated by Django 3.2.7 on 2022-03-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hl', '0014_notification_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='notification',
            field=models.ManyToManyField(blank=True, related_name='user_notification', to='hl.Notification'),
        ),
    ]
